name: Build Binary

on:
  push:
    branches: [ v1.22.3 ]
  pull_request:
    branches: [ v1.22.3 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: make quick-release
      run: make quick-release
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ github.run_id }}
        path: _output/bin/*
